apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - ../../../addons/overlays/dev/kube-prometheus-stack
  - metrics-server.yaml
  - ingress-nginx.yaml
  - weave-gitops.yaml
  - k8s-dashboard.yaml
  - cert-manager.yaml