---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1m0s
  path: ./addons/overlays/dev/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
