---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 1m0s
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    retries: 3
    

