---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 44.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 1m0s
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    grafana:
      ingress:
        enabled: true
    prometheus:

      serviceMonitorSelector:
        matchLabels:
          app.kubernetes.io/component: controller

      podMonitorSelector:
        matchLabels:
          app.kubernetes.io/component: monitoring

      ingress:
        enabled: true
      
      prometheusSpec:
        scrapeInterval: "10s"
        retention: 15d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              resources:
                requests:
                  storage: 10Gi
