---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 45.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 1m0s
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    alertmanager:
      config:
        receivers:
        - name: 'robusta'
          webhook_configs:
            - url: 'http://robusta-runner.default.svc.cluster.local/api/alerts'
              send_resolved: true
        
        route:
          routes:
          - receiver: 'robusta'
            match_re:
              severity: 'info|warn|error|critical'
            repeat_interval: 4h
            continue: true

