---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 48.3.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 1m0s
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    grafana:
      ingress:
        enabled: true
    prometheus:
      ingress:
        enabled: true
      
      prometheusSpec:
        podMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false

        scrapeInterval: "10s"
        retention: 15d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              resources:
                requests:
                  storage: 10Gi
