---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1m0s
  path: ./addons/base/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      INGRESS_CLASS: nginx
      DOMAIN: dev.devops.com